apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: recrea-sys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: backend-code
              mountPath: /var/www/html/backend
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: backend-code
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: recrea-sys
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP