apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: recrea-sys
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        root /var/www/html/backend/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            # En sidecar, php-fpm corre en localhost dentro del mismo pod
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_read_timeout 300;
        }

        location ~ /\. {
            deny all;
        }
    }