global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend-nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    # Si no tienes endpoint /metrics, usa el health check
    # metrics_path: '/health'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']